config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :messages
  resources :audiences
  resources :listings
  resources :jobs
  resources :organisations
  resources :skills
  resources :employments
  resources :cadetships
  resources :internships
  resources :awards
  resources :scholarships
  resources :university_educations
  resources :student_profiles
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  root 'pages#home'
  get 'pages/home'
  get 'pages/admin'
  get 'pages/events'
  get 'pages/programs'
  get 'pages/jobs'
  get 'pages/contact'
  get 'pages/approved_events'
  get 'pages/approved_programs'
  get 'pages/approved_jobs'
  get 'pages/universities'
  get 'pages/organisations'
  get 'pages/highschoolers'
  get 'pages/highschoolers_view_listings'
  get 'pages/uni_students'
  get 'pages/uni_students_listings'
  get 'pages/students_gallery'
  get 'pages/conversations'
  get 'pages/news'
  get 'pages/guides'
  get 'pages/about'
  get 'pages/privacy_policy'
  get 'pages/terms_conditions'

  devise_for :users

  resources :listings do
  	member do
  		get :remove_audience_from
  		get :add_audience_to
  	end
  end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :organisation
  has_many :listing_audiences
  has_many :audiences, through: :listing_audiences
  validates :title, :short_description, :long_description, :contact_name, :contact_email, :street_address, :suburb, :state, :postcode, :start_time, :end_time, presence: true

  scope :program_type,->{ where(listing_type: 'program') }
  scope :event_type,->{ where(listing_type: 'event') }
  scope :job_type,->{ where(listing_type: 'job') }
  scope :draft,->{ where(status: 'draft') }
  scope :approved,->{ where(status: 'approved') }
  scope :expired,->{ where(status: 'expired') }
  scope :archived,->{ where(status: 'archived') }
  scope :expires,->{where("expired_at < ?", Date.today)}

  validate :start_time_cannot_be_empty
  validate :end_time_cannot_be_empty
  validate :start_time_cannot_be_in_the_past
  validate :end_time_cannot_be_in_the_past
  validate :end_time_must_be_greater_than_start_time

  mount_uploader :image, ProfilePicUploader


  validates_presence_of :audiences, unless: :is_job_listing
  # audiences must be present only for listing type of event and program, but not for job
  # see http://guides.rubyonrails.org/active_record_validations.html#conditional-validation

  is_impressionable :counter_cache => true, :unique => :request_hash

  def self.check_for_expired_listings
    newly_expired_listings.each do |listing|
      listing.update_attributes(status: 'expired')
      listing.save!
    end
  end

  def self.newly_expired_listings
    where('expired_at < ? AND status != ?', Date.today, 'expired')
  end

  def is_job_listing
    listing_type == 'job'
  end

  def start_time_cannot_be_empty
    errors.add(:start_time, "can't be empty") if !start_time.present?
  end

  def end_time_cannot_be_empty
    errors.add(:end_time, "can't be empty") if !end_time.present?
  end

  def start_time_cannot_be_in_the_past
    errors.add(:start_time, "can't be in the past") if start_time.present? && start_time < Date.today
  end

  def end_time_cannot_be_in_the_past
    errors.add(:end_time, "can't be in the past") if end_time.present? && end_time < Date.today
  end

  def end_time_must_be_greater_than_start_time
    errors.add(:end_time, "must be after the start time") if end_time.present? && start_time.present? && end_time < start_time
  end

  def self.search(search)
    where("suburb ILIKE ? OR state ILIKE ? OR postcode ILIKE ? OR title ILIKE ? OR short_description ILIKE ? OR long_description ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :show
  before_action :set_listing, only: [:add_audience_to, :remove_audience_from, :show, :edit, :update, :destroy]
  impressionist :actions=>[:show]
  # GET /listings
  # GET /listings.json
  def index
    @listings = current_user.organisation.listings
    @events = @listings.event_type
    @jobs = @listings.job_type
    @programs = @listings.program_type
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    if params[:listing_type] && params[:org]
      @listing = Listing.new
      @audiences = Audience.all
      @audiences.each do |audience|
        @listing.audiences << audience
      end

    else
      redirect_to organisation_path(current_user.organisation)
    end

  end

  # GET /listings/1/edit
  def edit
    @audiences = Audience.all
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.organisation_id = current_user.organisation.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_audience_to
  	@audience = Audience.find(params[:audience])
  	@listing.audiences << @audience
  	redirect_to :back
  end

  def remove_audience_from
  	@audience = Audience.find(params[:audience])
  	@listing.audiences.delete(@audience)
  	redirect_to :back
  end

  def draft_events
    @listings = Listing.all
  end

  def newly_expired_listings
    where('expired_at > ? && status != ?', Date.today, 'expired')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:image, :listing_type, :title, :short_description, :long_description, :contact_name, :contact_email, :contact_phone, :website, :start_time, :end_time, :ticket_required, :official_hastag, :facebook_url, :twitter_handle, :instagram_handle, :job_category, :job_type, :salary, :organisation_id, :street_address, :suburb, :state, :postcode, :status, :impressions_count, :company_name, :ticket_website, :expired_at, :audience_ids => [])
    end
end

app/views/listings/_forbidden.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <div class="errormsg"><h5>Access to this page is not allowed.</h5></div>
  </div><!-- end of col s12 -->
</div><!-- end of row -->

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>

  <!-- lists through all the error messages, this has to be placed after the form_for loop -->
  <% if @listing.errors.any? %>
  <div class='errormsg'>
  <ul>
    <% @listing.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  </div>
  <% end %> <!-- end of listing error -->

  <div class="form-inputs">
    <% if params[:listing_type] %>
      <%= f.input :listing_type, as: :hidden, input_html: { value: params[:listing_type]}  %>
    <% end %>
    <%= f.input :title %>
    <%= f.input :short_description, input_html: { maxlength: 200 } %>
    <%= f.input :long_description, input_html: { maxlength: 1000 } %>
    <% if @listing.listing_type == 'job' ||  params[:listing_type] == 'job' %><!-- please keep job company_name in this position, do not move.  -->
      <%= f.input :company_name %>
    <% end %>
    <%= f.input :contact_name %>
    <%= f.input :contact_email %>
    <%= f.input :contact_phone %>
    <%= f.input :website %>
    <%= f.input :street_address %>
    <%= f.input :suburb %>
    <%= f.input :state, collection: ['NSW', 'ACT', 'VIC', 'QLD', 'SA', 'NT', 'TAS'] %>
    <%= f.input :postcode %>
    <%= f.input :image, label: 'Image or Company Logo:' %><br>

    <% if @listing.listing_type == 'job' ||  params[:listing_type] == 'job' %><!-- testing value for editing a job or for a new job  -->
      <% if @listing.start_time.present? %>
        <%= f.input :start_time, as: :string, label: 'Job Application Open Time (AEST):', input_html: { class: 'datetimepicker', value: localize(f.object.start_time, :format => "%d/%m/%Y  %I:%m %p")} %>
        <%= f.input :end_time, as: :string, label: 'Job Application Closing Time (AEST):', input_html: { class: 'datetimepicker', value: localize(f.object.end_time, :format => "%d/%m/%Y  %I:%m %p")} %>
      <% else %>
        <%= f.input :start_time, as: :string, label: 'Job Application Open Time (AEST):', input_html: { class: 'datetimepicker'} %>
        <%= f.input :end_time, as: :string, label: 'Job Application Closing Time (AEST):', input_html: { class: 'datetimepicker'} %>
      <% end %>
        <%= f.input :job_category, collection: ['full time', 'part time', 'casual', 'internship'] %>
      <%= f.input :job_type, collection: [ 'Accounting',
        'Administration Office Support',
        'Advertising, Arts & Media',
        'Banking & financial services',
        'Call Centre & Customer Service',
        'CEO & General Management',
        'Community Services & Development',
        'Construction',
        'Consulting & Strategy',
        'Design & Architecture',
        'Education & Training',
        'Engineering',
        'Farming, Animals & Conservation',
        'Government & Defence',
        'Healthcare & Medical',
        'Hospitality & Tourism',
        'Human Resources & Recruitment',
        'Information and Communication Technology',
        'Insurance & Superannuation',
        'Legal, Law Enforcement, Correctional Services',
        'Manufacturing, Transport & Logistics',
        'Marketing & Communications',
        'Mining, Resources & Energy',
        'Real Estate & Property',
        'Retail & Consumer Products',
        'Sales',
        'Science & Technology',
        'Self-Employment',
        'Sport & Recreation',
        'Trades and Services' ] %>
      <%= f.input :salary, label: 'Salary Range', collection: ['up to $30K', '$30K - $40K', '$40K - $50K', '$50K - $60K', '$60K - $70K', '$70K - $80K', '$80K - $90K', '$90K - $100K', '$100K - $120K', '$120K - $150K', '$150K - $200K', 'Hourly rates'] %>

    <% else %> <!-- else if it's an event or a program -->
      <% if @listing.start_time.present? %>
        <%= f.input :start_time, as: :string, label: 'Start Time (AEST):', input_html: { class: 'datetimepicker', value: localize(f.object.start_time, :format => "%d/%m/%Y  %I:%m %p")} %>
        <%= f.input :end_time, as: :string, label: 'End Time (AEST):', input_html: { class: 'datetimepicker', value: localize(f.object.end_time, :format => "%d/%m/%Y  %I:%m %p")} %>
      <% else %>
        <%= f.input :start_time, as: :string, label: 'Start Time (AEST):', input_html: { class: 'datetimepicker'} %>
        <%= f.input :end_time, as: :string, label: 'End Time (AEST):', input_html: { class: 'datetimepicker'} %>
      <% end %>
        <p>Choose Audiences:</p> <!-- only for events and programs, but not for jobs -->
          <% if (@listing.new_record?) %><!-- if the listing is never been recorded in database (new) -->
            <% @listing.audiences.each do |audience| %><!-- check all the audiences items -->
              <input class="" type="checkbox" value="<%= audience.id %>" name="listing[audience_ids][]" id="listing_audience_ids_<%= audience.id %>" checked />
              <label for="listing_audience_ids_<%= audience.id %>"><%= audience.name %></label>
              <% if audience.name == "highschool" %>
                <div class="taglines"><p>Mentoring, Development, Pre-Tertiary programs and Winter and Summer schools.</p></div>
              <% elsif audience.name == "undergraduate" %>
                <div class="taglines"><p>Direct Access: ATAR and OP, Indirect Access: Pathway, Enabling, Admissions, Preparatory and Bridging programs.</p></div>
              <% elsif audience.name == "postgraduate" %>
                <div class="taglines"><p>Masters, Honours and PhD programs.</p></div>
              <% elsif audience.name == "employment" %>
                <div class="taglines"><p>Internships, Cadetships, Traineeships and Jobs.</p></div>
              <% elsif audience.name == "community" %>
                <div class="taglines"><p>Aboriginal and Torres Strait Islander peoples and organisations.</p></div>
              <% end %>
              <br>
            <% end %><!-- end of loop -->
              <input type="hidden" name="listing[audience_ids][]" value="" /><!-- this is for when a box is unchecked, it will leave value '' (empty) must have this -->
          <% else %> <!-- if the listing is already from the database (not new record) -->
            <% @listing.audiences.each do |audience| %><!-- go through the audiences list and checked the ones already included -->
              <input class="" type="checkbox" value="<%= audience.id %>" name="listing[audience_ids][]" id="listing_audience_ids_<%= audience.id %>" <%= @listing.audiences.include?(audience) ? 'checked' : '' %> /> <!-- if the audience has been selected, it will be checked -->
              <label for="listing_audience_ids_<%= audience.id %>"><%= audience.name %></label>
              <br>
            <% end %><!-- end of loop -->
            <input type="hidden" name="listing[audience_ids][]" value="" /><!-- this is for when a box is unchecked, it will leave value '' (empty) must have this -->
          <% end %><!-- end choose audiences -->

      <% if @listing.listing_type == 'event' ||  params[:listing_type] == 'event' %>
        <%= f.input :ticket_required, label: 'Ticket Required?', collection: ['Tickets Essential', 'Bookings Essential', 'No Booking Required'] %>
        <%= f.input :ticket_website, label: 'Website to Book Tickets (if required):' %>
      <% elsif @listing.listing_type == 'program' ||  params[:listing_type] == 'program' %>
        <%= f.input :ticket_required, label: 'Ticket Required?', collection: ['Tickets Essential', 'Bookings Essential', 'No Booking Required', 'Applications Open', 'Applications Closing Soon'] %>
        <%= f.input :ticket_website, label: 'Website to Book Tickets (if required):' %>
      <% end %>
      <%= f.input :official_hastag %>
      <%= f.input :facebook_url %>
      <%= f.input :twitter_handle %>
      <%= f.input :instagram_handle %>
      <%= f.input :image %>
    <% end %><!-- end of testing value for editing a job or for a new job  -->
    <% if current_user.has_role? :admin %>
      <% if @listing.expired_at.present? %>
        <%= f.input :expired_at, as: :string, label: 'Expired At (AEST):', input_html: { class: 'datetimepicker', value: localize(f.object.start_time, :format => "%d/%m/%Y  %I:%m %p")} %>
      <% else %>
        <%= f.input :expired_at, as: :string, label: 'Expired At (AEST):', input_html: { class: 'datetimepicker'} %>
      <% end %>
      <%= f.input :status, collection: ['draft', 'approved', 'archived']%>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %><!-- end of simple form -->

<% if user_signed_in? %>
  <% if @listing.organisation.present? %><!-- if editing a listing, not for creating a new listing-->
    <% if @listing.organisation.user == current_user %>
      <%= link_to 'Show', @listing %> |
      <%= link_to 'Back', :back %>
    <% elsif current_user.has_role? :admin %>
      <%= link_to 'Show', @listing %> |
      <%= link_to 'Back to Admin', pages_admin_path %>
    <% else %>
      <%= render 'forbidden' %>
    <% end %>
  <% end %>
<% end %>

app/views/listings/_listing.html.erb
<ul class="collection">
  <li class="collection-item avatar">
    <% if listing.image_url.present? %>
      <%= cl_image_tag(listing.image_url, alt: "", class: "circle",) %>
    <% else %>
      <%= cl_image_tag("default_pic2_otesv3.png", alt: "", class: "circle") %>
    <% end %>
    <span class="title"><p><%= link_to listing.title, listing_path(listing.id) %></p></span>
    <p><%= listing.short_description %></p>
    <% unless current_page?(root_path) || current_page?(pages_approved_events_path) || current_page?(pages_approved_programs_path) || current_page?(pages_approved_jobs_path) %>
      <% if user_signed_in? %>
        <% if listing.organisation.user == current_user %>
          <%= link_to 'Edit', edit_listing_path(listing), class: 'btn' %>
        <% end %>
        <% if current_user.has_role? :admin %>
          <%= link_to 'Edit', edit_listing_path(listing), class: 'btn' %>
        <% end %>
      <% end %><!-- end if user signed in -->
    <% end %><!-- end of unless current page is root path -->
  </li>
    <!-- DO NOT USE THE BLOCK OF LINES BELOW -->
    <!-- <% if listing.audiences.any? %>
      <div class="taglines"><p>Can't delete this listing if an audience is still attached to it.</p></div>
    <% else %>
      <%= link_to 'Delete', listing_path(listing), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-destroy' %>
    <% end %> -->
</ul>

app/views/listings/edit.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <% if user_signed_in? %>
      <% if (@listing.organisation.user == current_user) || (current_user.has_role? :admin) %>
        <h3>Editing <%= @listing.listing_type %></h3>
        <%= render 'form' %>
      <% else %>
        <%= render 'forbidden' %>
      <% end %>
    <% end %>
  </div><!-- end of col s12 -->
</div><!-- end of row -->

app/views/listings/index.html.erb
<h3>My Listings</h3>

<h5>Events</h5>
  <% if @events.organisation.any? %>
    <%= render @events %> <!-- render @events will call the _listing.html.erb -->
  <% else %>
    <div class="taglines"><p>Currently no event listed</p></div>
  <% end %>

<h5>Programs</h5>
  <% if @programs.organisation.any? %>
    <%= render @programs %>
  <% else %>
    <div class="taglines"><p>Currently no program listed</p></div>
  <% end %>

<h5>Jobs</h5>
<% if @jobs.organisation.any? %>
  <%= render @jobs %>
<% else %>
  <div class="taglines"><p>Currently no job listed</p></div>
<% end %>

<div class="form-actions">
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-success' %>
</div>

app/views/listings/new.html.erb
<div class="row">
  <div class="col s12 m8 offset-m2 l8 offset-l2">
    <h3>Add <%= params[:listing_type] %></h3>
    <%= render 'form' %>
    <%= link_to 'Back', listings_path %>
  </div><!-- end of col s12 -->
</div><!-- end of row -->

app/views/listings/show.html.erb
<%= content_for :title, @listing.title %>
  <div class="row">
    <div class="col s12 m12 l12"><p id="notice"><%= notice %></p></div>
      <% @listing.impressionist_count(:filter=>:session_hash, :unique=>true) %>
    <div class="col s12 m12 l12">
      <% if @listing.image_url.present? %>
        <%= cl_image_tag(@listing.image_url, :size => "300") %>
      <% else %>
        <%= cl_image_tag("default_pic2_otesv3.png", :size => "300", :opacity=>33) %>
      <% end %>        </div>
      <% if @listing.listing_type == 'job' %><!-- job vacancy sign if still open or closed -->
        <% if Date.today < (@listing.end_time) %>
          <div class="col s12 m12 l12 taglines"><a class="btn disabled"><i class="material-icons right">lock_open</i>Job vacancy is still open.</a></div>
        <% else %>
          <div class="col s12 m12 l12 taglines"><a class="btn disabled"><i class="material-icons right">lock_closed</i>Job vacancy is closed.</a></div>
        <% end %>
      <% end %>
      <br>
        <div class="col s4 m2 l3"><p>Listing Type:</p></div>
        <div class="col s8 m10 l9"><p><%= @listing.listing_type %></p></div>
        <div class="col s3 m2 l3"><p>Listing ID:</p></div>
        <div class="col s9 m10 l9"><p><%= @listing.id %></p></div>
        <div class="col s2 m2 l3"><p>Title:</p></div>
        <div class="col s10 m10 l9"><p><%= @listing.title %></p></div>
        <div class="col s12 m12 l12"><p>Short Description:<br><%= @listing.short_description %></p></div>
        <div class="col s12 m12 l12"><p>Long Description:<br><%= @listing.long_description %></p></div>
        <% if @listing.listing_type == 'job' %>
          <div class="col s4 m2 l3"><p>Company Name:</p></div>
          <div class="col s6 m10 l9"><p><%= @listing.company_name %></p></div>
        <% end %>
        <div class="col s5 m3 l3"><p>Contact Name:</p></div>
        <div class="col s5 m9 l9"><p><%= @listing.contact_name %></p></div>
        <div class="col s4 m2 l3"><p>Email:</p></div>
        <div class="col s6 m10 l9"><p><%= @listing.contact_email %></p></div>
        <div class="col s4 m2 l3"><p>Phone:</p></div>
          <% if @listing.contact_phone.present? %>
            <div class="col s6 m10 l9"><p><%= @listing.contact_phone %></p></div>
          <% else %>
            <div class="col s6 m10 l9"><p>_</p></div>
          <% end %>
        <div class="col s4 m2 l3"><p>Website:</p></div>
          <% if @listing.website.present? %>
            <div class="col s6 m10 l9"><p><a href="http://<%= @listing.website %>"><%= @listing.website %></a></p></div>
          <% else %>
            <div class="col s6 m10 l9"><p>_</p></div>
          <% end %>
        <div class="col s4 m2 l3"><p>Street:</p></div>
        <div class="col s6 m10 l9"><p><%= @listing.street_address %></p></div>
        <div class="col s4 m2 l3"><p>Suburb:</p></div>
        <div class="col s6 m10 l9"><p><%= @listing.suburb %></p></div>
        <div class="col s4 m2 l3"><p>State:</p></div>
        <div class="col s6 m10 l9"><p><%= @listing.state %></p></div>
        <div class="col s4 m2 l3"><p>Postcode:</p></div>
        <div class="col s6 m10 l9"><p><%= @listing.postcode %></p></div>
          <% if @listing.listing_type == 'event' || @listing.listing_type == 'program' %>
            <% if user_signed_in? %>
              <% unless current_user.has_role? :admin %><!-- only admin can see the audiences -->
              <div class="col s4 m3 l3"><p>Audiences:</p></div>
                <% @listing.audiences.each do |audience| %>
                  <div class="col s12 m12 l12"><a class="btn-flat btn-disabled"><%= audience.name %></a></div>
                <% end %>
            <% end %>
          <% end %>
          <div class="col s4 m3 l3"><p>Start time (AEST):</p></div>
            <% if @listing.start_time %>
              <div class="col s6 m9 l9"><p><%= @listing.start_time.strftime("%A, %d %b %Y %l:%M %p") %></p></div>
            <% end %>
          <div class="col s4 m3 l3"><p>End time (AEST):</p></div>
            <% if @listing.end_time %>
              <div class="col s6 m9 l9"><p><%= @listing.end_time.strftime("%A, %d %b %Y %l:%M %p") %></p></div>
            <% end %>

          <% if @listing.ticket_required.present? %>
            <p>
              <div class="col s12 m12 l12"><br>Ticket Booking or Opening Status:</div>
              <div class="col s12 m12 l12"><%= @listing.ticket_required %></div>
            </p>
          <% end %>

          <% if @listing.ticket_website.present? %>
            <p>
              <div class="col s5 m3 l3"><br>Ticket Website:</div>
              <div class="col s12 m9 l9"><a href="http://<%= @listing.ticket_website %>"><%= @listing.ticket_website %></a></div>
            </p>
          <% end %>

          <% if @listing.official_hastag.present? %>
            <p>
              <div class="col s12 m12 l12"><br>Official hastag:</div>
              <div class="col s12 m12 l12"><%= @listing.official_hastag %></div>
            </p>
          <% end %>

          <% if @listing.facebook_url.present? %>
            <p>
              <div class="col s12 m12 l12"><br>Facebook URL:</div>
              <div class="col s12 m12 l12"><a href="http://<%= @listing.website %>"><%= @listing.facebook_url %></a></div>
            </p>
          <% end %>

          <% if @listing.twitter_handle.present? %>
            <p>
              <div class="col s12 m12 l12"><br>Twitter Handle:</div>
              <div class="col s12 m12 l12"><%= @listing.twitter_handle %></div>
            </p>
          <% end %>

          <% if @listing.instagram_handle.present? %>
            <p>
              <div class="col s12 m12 l12"><br>Instagram Handle:</div>
              <div class="col s12 m12 l12"><%= @listing.instagram_handle %></div>
            </p>
          <% end %>

        <% else %><!-- else if listing type is job -->
          <div class="col s12 m4 l3"><p>Application Open Date (AEST):</p></div>
          <div class="col s12 m8 l9"><p><%= @listing.start_time.strftime("%A, %d %b %Y %l:%M %p") %></p></div>
          <div class="col s12 m4 l3"><p>Application Closing Date (AEST):</p></div>
          <div class="col s12 m8 l9"><p><%= @listing.end_time.strftime("%A, %d %b %Y %l:%M %p") %></p></div>
          <div class="col s12 m2 l3"><p>Job category:</p></div>
            <% if @listing.job_category.present? %>
              <div class="col s12 m10 l9"><p><%= @listing.job_category %></p></div>
            <% else %>
              <div class="col s12 m10 l9"><p>_</p></div>
            <% end %>
          <div class="col s12 m2 l3"><p>Job type:</p></div>
            <% if @listing.job_type.present? %>
              <div class="col s12 m10 l9"><p><%= @listing.job_type %></p></div>
            <% else %>
              <div class="col s12 m10 l9"><p>_</p></div>
            <% end %>
          <div class="col s12 m2 l3"><p>Salary:</p></div>
            <% if @listing.salary.present? %>
              <div class="col s12 m10 l9"><p><%= @listing.salary %></p></div>
            <% else %>
              <div class="col s12 m10 l9"><p>_</p></div>
            <% end %>

          <div class="col s12 m2 l3"><p>Organiser:</p></div>
          <div class="col s12 m10 l9"><p><%= @listing.organisation.company_name %></p></div>
        <% end %> <!-- end of unless if it's a job type -->

        <% if user_signed_in? %>
          <% if @listing.organisation.user == current_user %>
            <div class="col s12 m2 l3"><p>Listing Status: </p></div>
            <div class="col s12 errormsg"><p><%= @listing.status %></p></div>
            <div class="col s6 m2 l3"><p>Number of Views: </p></div>
            <div class="col s4 m10 l9"><p><%= @listing.impressions_count%></p></div>
            <div class="col s12 m12 l12"><a class="waves-effect waves-light btn palette4-bg" href="/listings/<%= @listing.id %>/edit">Edit</a></div>
          <% elsif current_user.has_role? :admin %>
            <div class="col s5 m3 l3"><p>Listing Expired At: </p></div>
            <% if @listing.expired_at %>
              <div class="col s5 m9 l9 errormsg"><p><%= @listing.expired_at.strftime("%A, %d %b %Y %l:%M %p") %></p></div>
            <% else %>
              <div class="col s5 m9 l9"><p>No expiry date.</p></div>
            <% end %>
            <br>
            <div class="col s12">
              <%= link_to 'Edit', edit_listing_path(@listing) %> |
              <%= link_to 'Back to Admin', pages_admin_path %>
            </div>
          <% end %>
        <% end %>
    </div><!-- end of row -->