config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :messages
  resources :audiences
  resources :listings
  resources :jobs
  resources :organisations
  resources :skills
  resources :employments
  resources :cadetships
  resources :internships
  resources :awards
  resources :scholarships
  resources :university_educations
  resources :student_profiles
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  root 'pages#home'
  get 'pages/home'
  get 'pages/admin'
  get 'pages/events'
  get 'pages/programs'
  get 'pages/jobs'
  get 'pages/contact'
  get 'pages/approved_events'
  get 'pages/approved_programs'
  get 'pages/approved_jobs'
  get 'pages/universities'
  get 'pages/organisations'
  get 'pages/highschoolers'
  get 'pages/highschoolers_view_listings'
  get 'pages/uni_students'
  get 'pages/uni_students_listings'
  get 'pages/students_gallery'
  get 'pages/conversations'
  get 'pages/news'
  get 'pages/guides'
  get 'pages/about'
  get 'pages/privacy_policy'
  get 'pages/terms_conditions'

  devise_for :users

  resources :listings do
  	member do
  		get :remove_audience_from
  		get :add_audience_to
  	end
  end

end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  belongs_to :student_profile
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  before_action :set_scholarship, only: [:show, :edit, :update, :destroy]

  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
  end

  # GET /scholarships/new
  def new
    @scholarship = Scholarship.new
  end

  # GET /scholarships/1/edit
  def edit
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(scholarship_params)

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship.student_profile, notice: 'Scholarship was successfully created.' }
        format.json { render :show, status: :created, location: @scholarship.student_profile }
      else
        format.html { render :new }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scholarships/1
  # PATCH/PUT /scholarships/1.json
  def update
    respond_to do |format|
      if @scholarship.update(scholarship_params)
        format.html { redirect_to @scholarship.student_profile, notice: 'Scholarship was successfully updated.' }
        format.json { render :show, status: :ok, location: @scholarship.student_profile }
      else
        format.html { render :edit }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship.destroy
    respond_to do |format|
      format.html { redirect_to @scholarship.student_profile, notice: 'Scholarship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scholarship
      @scholarship = Scholarship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scholarship_params
      params.require(:scholarship).permit(:title, :organisation, :year_received, :student_profile_id)
    end
end

app/views/scholarships/_form.html.erb
<%= simple_form_for(@scholarship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, input_html: { maxlength: 80 } %>
    <%= f.input :organisation, input_html: { maxlength: 80 } %>
    <%= f.input :year_received, input_html: { maxlength: 4 } %>
    <% if params[:student_profile_id] %>
      <%= f.input :student_profile_id, :as => :hidden, input_html: { value: params[:student_profile_id]} %>
      <!-- Use the :input_html option  to pass any html attribute (:student_profile_id) straight to the input -->
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scholarships/edit.html.erb
<% if user_signed_in? %>
  <% if current_user.id == @scholarship.student_profile.user.id %>
    <div class="row">
      <div class="col s12 m8 offset-m2 l8 offset-l2">
        <p>
          <h4>Editing Scholarship</h4>
          Max. 80 characters for each label.
        </p>
        <%= render 'form' %>
      </div>
    </div>
  <% else %>
    <%= render "listings/forbidden" %>
  <% end %>
<% end %>

app/views/scholarships/index.html.erb
<h1>Listing scholarships</h1>

<table class="table">
    <tr>
      <th>Title</th>
      <th>Organisation</th>
      <th>Year_received</th>
      <th>Student_profile</th>
        <th colspan="3"></th>
    </tr>

  <%= content_tag_for(:tr, @scholarships) do |scholarship| %>
    <td><%= scholarship.title %></td>
    <td><%= scholarship.organisation %></td>
    <td><%= scholarship.year_received %></td>
    <td><%= scholarship.student_profile %></td>
      <td><%= link_to 'Show', scholarship %></td>
    <td><%= link_to 'Edit', edit_scholarship_path(scholarship), class: 'btn btn-edit' %></td>
    <td><%= link_to 'Delete', scholarship, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-destroy' %></td>
  <% end %>
</table>


<div class="form-actions">
  <%= link_to 'New Scholarship', new_scholarship_path, class: 'btn btn-success' %>
</div>

app/views/scholarships/new.html.erb
<% if user_signed_in? %>
  <% if current_user.student_profile.id == params[:student_profile_id].to_i %>
    <div class="row">
      <div class="col s12 m8 offset-m2 l8 offset-l2">
        <p>
          <h4>New Scholarship</h4>
          Max. 80 characters for each label.
        </p>
        <%= render 'form' %>
      </div>
    </div>
  <% else %>
    <%= render "listings/forbidden" %>
  <% end %>
<% end %>

app/views/scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scholarship.title %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @scholarship.organisation %>
</p>

<p>
  <strong>Year received:</strong>
  <%= @scholarship.year_received %>
</p>

<p>
  <strong>Student profile:</strong>
  <%= @scholarship.student_profile %>
</p>

<%= link_to 'Edit', edit_scholarship_path(@scholarship) %> |
<%= link_to 'Back', scholarships_path %>