config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :messages
  resources :audiences
  resources :listings
  resources :jobs
  resources :organisations
  resources :skills
  resources :employments
  resources :cadetships
  resources :internships
  resources :awards
  resources :scholarships
  resources :university_educations
  resources :student_profiles
  get 'admin', to: 'pages#admin'
  get 'contact', to: 'pages#contact'
  root 'pages#home'
  get 'pages/home'
  get 'pages/admin'
  get 'pages/events'
  get 'pages/programs'
  get 'pages/jobs'
  get 'pages/contact'
  get 'pages/approved_events'
  get 'pages/approved_programs'
  get 'pages/approved_jobs'
  get 'pages/universities'
  get 'pages/organisations'
  get 'pages/highschoolers'
  get 'pages/highschoolers_view_listings'
  get 'pages/uni_students'
  get 'pages/uni_students_listings'
  get 'pages/students_gallery'
  get 'pages/conversations'
  get 'pages/news'
  get 'pages/guides'
  get 'pages/about'
  get 'pages/privacy_policy'
  get 'pages/terms_conditions'

  devise_for :users

  resources :listings do
  	member do
  		get :remove_audience_from
  		get :add_audience_to
  	end
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :organisation
  is_impressionable :counter_cache => true
  mount_uploader :picture, ProfilePicUploader
  mount_uploader :video, ProfilePicUploader

  validates :title, :author, :description, :categories, presence: true
  scope :on,->{ where(published: 'on') }

  def self.search(search)
     where("title ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :published, :date_published, :author, :description, :categories, :picture, :weblink, :youtube, :video, :impressions_count, :organisation_id)
    end
end

app/views/news/_form.html.erb
<%= simple_form_for(@news) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, input_html: { maxlength: 100 } %>
    <%= f.input :published, label: 'Publish this news?', collection: ['off','on'] %>
    <% if @news.published == 'On' %>
      <% @news.date_published = Date.today %>
    <% end %>
    <%= f.input :author %>
    <%= f.input :description, input_html: { maxlength: 250 } %>
    <%= f.input :categories, collection: [
      'Architecture and Building',
      'Agriculture, Environmental & Related Studies',
      'Mixed Field Programs',
      'Natural & Physical Sciences',
      'Education',
      'Health',
      'Information Technology',
      'Engineering and related technologies',
      'Creative Arts',
      'Management & Commerce',
      'Law, Society & Culture'] %>
    <%= f.input :picture, label: 'Picture (Max size 450 pixels x 250 pixels)' %>
    <%= f.input :weblink, label: 'Web Link (do not include http://)' %>
    <%= f.input :youtube, label: 'YouTube URL (do not include http://)' %>
    <%#= f.input :video %><!-- not required, use YouTube account instead-->
    <%# f.input :impressions_count %><!-- not yet tested -->
    <%= f.association :organisation, :as => :hidden, input_html: { value: params[:org_id]} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<% if current_user.organisation.id == @news.organisation_id %>
  <div class="row">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
      <%@org_id = params[:org_id]%>
      <h1>Editing News</h1>
      <%= render 'form' %>
    </div>
  </div>
<% else %>
  <%= render "listings/forbidden" %>
<% end %>

app/views/news/index.html.erb
<% @organisation = Organisation.find(params[:org_id]) %>
<% if @organisation.id == current_user.organisation.id %>
  <div class="row">
    <div class="col s12 m12 l12">
      <h4 style="text-align: center;">News Index</h4>

      <% @news = @organisation.news %>
      <div class="form-actions" style="text-align: center; margin-top: 30px; margin-bottom: 40px;">
        <%= link_to 'Create News', new_news_path(org_id: @organisation.id), class: 'btn btn-success', style: 'background-color: #e64630' %>
      </div>

      <div class="col s12 m8 offset-m2 l8 offset-l2" style="margin-bottom: 20px;">
        <%= form_tag(pages_news_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search word in Title or Description"%>
          <button class="btn waves-effect waves-light palette4-bg" type="submit" name="commit" value="Search">SEARCH</button>
        <% end %>
      </div>

      <% if @news.present? %>
        <br>
        <% @news.each do |news| %>
          <div class="col s12 m8 offset-m2 l8 offset-l2">
          <div class="card">
            <div style="margin-left: 40px; margin-right: 40px; margin-top: 40px; margin-bottom: 40px;">

            <div class="row" style="margin: 0px; text-align: center;">
              <div class="col s12 m6 l6" style="margin-top: 0px; padding-bottom: 20px;">
                <h5>Image</h5>
                <% if news.picture.present? %>
                  <div class="embed-container" style="margin: 0px; padding-top: 0px; max-height: 250px;">
                    <%= cl_image_tag(news.picture_url, :width => "100%", :crop => :fill) %>
                    <!-- <img src=<%=news.picture%>> -->
                  </div>
                <% end %>
              </div>
              <div class="col s12 m6 l6" style="margin-top: 0px; padding-bottom: 20px;">
                <h5>YouTube</h5>
                <% if news.picture.present? %>
                  <div class="embed-container" style="margin: 0px; max-height: 250px;">
                    <%= embed(news.youtube)%>
                  </div>
                <% end %>
              </div>
            </div><!-- end of row -->

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Title: <span style="font-weight: normal;"><%= news.title %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Published Status: <span style="font-weight: normal;"><%= news.published %></span>
            </p>

            <% if news.date_published.present? %>
            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Published Date: <span style="font-weight: normal;"><%= news.date_published %></span>
            </p>
            <% end %>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Author: <span style="font-weight: normal;"><%= news.author %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Created At: <span style="font-weight: normal;"><%= news.created_at.strftime('%d %b, %Y') %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Updated At: <span style="font-weight: normal;"><%= news.updated_at.strftime('%d %b, %Y') %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Organisation: <span style="font-weight: normal;"><%= news.organisation.company_name %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Description: <span style="font-weight: normal;"><%= news.description %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Categories: <span style="font-weight: normal;"><%= news.categories %></span>
            </p>

            <% if news.picture.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Picture: <span style="font-weight: normal;"><%= news.picture %></span>
              </p>
            <% end %>

            <% if news.weblink.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Weblink: <span style="font-weight: normal;"><a href="http://<%= news.weblink %>"><%= news.weblink %></a></span>
              </p>
            <% end %>

            <% if news.youtube.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Youtube: <span style="font-weight: normal;"><a href="http://<%= news.youtube %>"><%= news.youtube %></a></span>
              </p>
            <% end %>

            <% if news.video.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Video: <span style="font-weight: normal;"><%= news.video %></span>
              </p>
            <% end %>

            <%# if news.impressions_count.present? %>
              <!-- <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Impressions_count: <span style="font-weight: normal;"><%= news.impressions_count %></span>
              </p> -->
            <%# end %> <!-- not tested -->

          <div style="margin-top: 10px; margin-bottom: 10px; margin-left: 10px;">
            <td><%= link_to 'Edit', edit_news_path(news, org_id: @organisation.id), class: 'btn btn-edit', style: "background-color: #00a2b4" %></td>
            <td><%= link_to 'Delete', news, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-destroy', style: "background-color: #00a2b4" %></td>
          </div>
          </div>
          </div><!-- end of card -->
          </div>
        <% end %><!-- end of loop -->

      <% else %>
        <p>There are no news related to <%= params[:search] %>.</p>
      <% end %>
    </div>
  </div>
<% else %>
  <%= render "listings/forbidden" %>
<% end %><!-- end of if @organisation.id == current_user.organisation.id -->

app/views/news/new.html.erb
<% if current_user.organisation.id == params[:org_id].to_i %>
  <div class="row">
    <div class="col s12 m8 offset-m2 l8 offset-l2">
      <h1>Create News</h1>
      <%= render 'form' %>
      <%= link_to 'Back', news_index_path %>
    </div><!-- end of col s12 -->
  </div><!-- end of row -->
<% else %>
  <%= render "listings/forbidden" %>
<% end %>

app/views/news/show.html.erb
<% if current_user.organisation.id == @news.organisation_id %>
  <div class="row">
    <div class="col s12">
      <p id="notice"><%= notice %></p>
      <div class="col s12 m8 offset-m2 l8 offset-l2">
        <div class="card">
          <div style="margin-left: 40px; margin-right: 40px; margin-top: 40px; margin-bottom: 40px;">

            <div class="row" style="margin: 0px; text-align: center;">
              <div class="col s12 m6 l6" style="margin-top: 0px; padding-bottom: 20px;">
                <h5>Image</h5>
                <% if @news.picture.present? %>
                  <div class="embed-container" style="margin: 0px; padding-top: 0px; max-height: 250px;">
                    <%= cl_image_tag(@news.picture_url, :width => "100%", :crop => :fill) %>
                  </div>
                <% end %>
              </div>
              <div class="col s12 m6 l6" style="margin-top: 0px; padding-bottom: 20px;">
                <h5>YouTube</h5>
                <% if @news.youtube.present? %>
                  <div class="embed-container" style="margin: 0px; max-height: 250px;">
                    <%= embed(@news.youtube)%>
                  </div>
                <% end %>
              </div>
            </div><!-- end of row -->

            <div style="text-align: center; margin-top: 5px;">

            </div>
            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Title: <span style="font-weight: normal;"><%= @news.title %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Published Status: <span style="font-weight: normal;"><%= @news.published %></span>
            </p>

            <% if @news.date_published.present? %>
            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Published Date: <span style="font-weight: normal;"><%= @news.date_published %></span>
            </p>
            <% end %>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Author: <span style="font-weight: normal;"><%= @news.author %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Organisation: <span style="font-weight: normal;"><%= @news.organisation.company_name %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Description: <span style="font-weight: normal;"><%= @news.description %></span>
            </p>

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Categories: <span style="font-weight: normal;"><%= @news.categories %></span>
            </p>

            <% if @news.picture.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Picture: <span style="font-weight: normal;"><%= @news.picture %></span>
              </p>
            <% end %>

            <% if @news.weblink.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Weblink: <span style="font-weight: normal;"><a href="http://<%= @news.weblink %>"><%= @news.weblink %></a></span>
              </p>
            <% end %>

            <% if @news.youtube.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Youtube: <span style="font-weight: normal;"><a href="http://<%= @news.youtube %>"><%= @news.youtube %></a></span>
              </p>
            <% end %>

            <% if @news.video.present? %>
              <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Video: <span style="font-weight: normal;"><%= @news.video %></span>
              </p>
            <% end %>

            <%# if @news.impressions_count.present? %>
              <!-- <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
                Impressions_count: <span style="font-weight: normal;"><%#= @news.impressions_count %></span>
              </p> -->
            <%# end %><!-- not yet tested -->

            <p style="margin-bottom: 5px; margin-left: 10px; margin-right: 10px; font-weight: bold;">
              Organisation ID: <span style="font-weight: normal;"><%= @news.organisation_id %></span>
            </p>

            <a href="/news?org_id=<%= @news.organisation_id %>" class="waves-effect waves-light btn palette4-bg" style="background-color: #00a2b4; margin-top: 5px; margin-left: 10px;">Back To News Index</a>
          </div><!-- end of div style -->
        </div><!-- end of card -->

      </div><!-- end of col s12 m8 offset-m2 l8 offset-l2 -->
    </div><!-- col s12 -->
  </div><!-- end of row -->
<% else %>
  <%= render "listings/forbidden" %>
<% end %>